### ISSUE TITLE
App name contains part of GTK trademark

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.github.gtkwave.GTKWave#19]
https://foundation.gnome.org/legal-and-trademarks/

Please rename it to not contain "GTK" and something distinct. I think 2 months is a reasonable time to come to a solution here.

**Comment by aklsh** [comment]
This issue should be raised in https://github.com/gtkwave/gtkwave as that is the main repository. This is just a flatpak packaging of it.

**Comment by bbhtt** [comment]
Please contact upstream about it, then, I don't know who's maintaining it. And please keep this open.

If the name is not changed we will be forced to delist and archive it from Flathub.

**Comment by bbhtt** [comment]
Hi, after some internal discussion it seems that there is no official policy from GNOME dictating whether third party applications can or cannot include "GTK" in their branding and whether that constitutes a trademark violation or fair use.

This makes enforcing a case of trademark violation complicated/not possible from our part. So we won't be pursuing this issue any further.

Sorry for any trouble it might have caused. Thanks!
