### ISSUE TITLE
Use flathubbot to detect new GTKWave releases

### ISSUE THREAD

**Issue by rfuest** [flathub/io.github.gtkwave.GTKWave#3]
Some GTKWave users did recently run into problems with the Flatpak version when they tried to load FST files. This issue has been fixed in GTKWave 3.3.115, but the version on Flathub hasn't been updated yet.

I would suggest to add support for the [`flatpak-external-data-checker`](https://github.com/flathub/flatpak-external-data-checker) to the manifest to automatically detect new releases. The README contains an example how the SF.net RSS feed can be used to detect new tarball releases: https://github.com/flathub/flatpak-external-data-checker#html-checker

**Comment by aklsh** [comment]
Done in #4.

**Comment by aklsh** [comment]
looks like it worked and has updated the flatpak correctly.
